#!/usr/bin/env python3
"""css + README emitter — reuses the canon model from gen.py. Run gen.py first."""
import sys, os, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen as G

OUT = G.OUT
brand = open(f"{OUT}/BRAND.md").read()          # the authority document, in-repo

m = re.search(r"(## THE SEVEN LAWS.*?)\n## Component inventory", brand, re.S)
assert m, "could not locate the Seven Laws section in BRAND.md"
ANNEX = m.group(1).rstrip("\n")

# ---------- css/bands-and-fields.css ----------
def rule_field(motif, ground):
    uri = G.data_uri(G.field_tile_svg(G.M[motif], ground))
    tw = G.M[motif]["cols"] * int(G.FIELD_MOD)
    th = G.M[motif]["rows"] * int(G.FIELD_MOD)
    ink, a = G.ink_for(ground)
    return (f"/* {motif} on {ground} — ink {ink} @ {a} */\n"
            f".field-{motif}-{ground}{{background-color:{G.GROUNDS[ground]};"
            f"background-image:url(\"{uri}\");"
            f"background-repeat:repeat;background-size:{tw}px {th}px}}\n")

def rule_band(cls, svg, w, h, repeat, bed=None):
    uri = G.data_uri(svg)
    bg = f"background-color:{bed};" if bed else ""
    return (f".{cls}{{height:{h}px;width:100%;{bg}"
            f"background-image:url(\"{uri}\");"
            f"background-repeat:{repeat};background-position:center;"
            f"background-size:{w}px {h}px}}\n")

css = [
    "/* ACP BRAND KIT — bands & fields as ready-to-paste data-URI background rules.",
    "   Generated by tools/docs.py from canon. Do not hand-edit: regenerate.",
    "   FIELD LAW v1.2 — shadow #040519 @0.18 on light/mid grounds; peri #6F7BFF @0.16 on dark.",
    "   BAND LAW v1.2 — bands never swap grounds. Scale by whole-number multiples only. */\n",
    "\n/* ============ BANDS ============ */\n",
    "/* Eternal Thread — dark grounds only. 18px is its native height. */\n",
]
css.append(rule_band("band-eternal-thread", G.band_eternal_thread(), 54, 18, "repeat-x", G.ABYSS))
css.append("\n/* Light Trim — LIGHT GROUNDS ONLY. Transparent ground: it takes the surface\n"
           "   beneath it. 32x8 unit; the canon 768x8 strip is this unit repeated 24x, which\n"
           "   repeat-x produces for free. */\n")
css.append(rule_band("band-light-trim", G.band_light_trim(), 32, 8, "repeat-x"))
css.append("\n/* Deco Band — editorial moments, white ground. */\n")
css.append(rule_band("band-deco", G.band_deco(), 88, 66, "repeat-x", G.WHITE))

css.append("\n/* ============ FIELDS ============ */\n")
for motif in G.MOTIFS:
    for ground in G.GROUNDS:
        css.append(rule_field(motif, ground))

G.wf(f"{OUT}/css/bands-and-fields.css", "".join(css))

# ---------- tools/requirements.txt ----------
G.wf(f"{OUT}/tools/requirements.txt",
     "# The loom's dependencies. Python 3.9+.\n"
     "#   pip install -r tools/requirements.txt\n"
     "# CairoSVG needs the native cairo library, which pip does NOT provide:\n"
     "#   macOS:  brew install cairo\n"
     "#   Debian: apt-get install libcairo2\n"
     "cairosvg>=2.7\n"
     "pillow>=10.0\n")

# ---------- README.md ----------
def tree():
    lines = []
    for d in ["sources", "motifs", "fields", "bands", "mixed", "css", "marks", "tools"]:
        fs = sorted(os.listdir(f"{OUT}/{d}"))
        fs = [f for f in fs if f != "__pycache__"]
        lines.append(f"\n### `/{d}/` — {len(fs)} files\n")
        if d == "fields":
            lines.append("Silhouette-dialect fields, one motif per file, on the six deployed grounds. "
                         "`.svg` is a 480x480 swatch carrying the tile as a `<pattern>`; `.png` is the "
                         "same at 2x (960x960).\n\n```\n")
            lines.append("\n".join(f"field_{m}_{{{','.join(G.GROUNDS)}}}.{{svg,png}}" for m in G.MOTIFS))
            lines.append("\n```\n")
        elif d == "mixed":
            lines.append("20 seeded Mixed Fields on ivory + abyss, even shuffle, silhouette dialect. "
                         "A seed produces one layout; that layout is rendered on both grounds.\n\n"
                         "**All 20 seeds reviewed and Commander-approved, 28 July 2026. The full set "
                         "is canon.**\n\n```\n"
                         "mix_s{1..20}_{ivory,abyss}.svg\ncontact-sheet.png\n```\n")
        elif d == "sources":
            lines.append("The canonical inputs. **Not build output — do not regenerate these.** "
                         "The loom reads them; everything else in this repo is derived from them.\n\n```\n"
                         + "\n".join(fs) + "\n```\n")
        else:
            lines.append("```\n" + "\n".join(fs) + "\n```\n")
    return "".join(lines)

readme = f"""# acp-brand-kit

Batch export of the ACP canon into ready-to-use assets. **This repo draws nothing new** — it
tiles, re-grounds, and packages motifs that already exist in the ACP Design System Figma file
and on the deployed portfolio.

The authority document is [`BRAND.md`](BRAND.md) (v1.1). Where this README and `BRAND.md`
disagree, `BRAND.md` wins.

---

## Law Annex

*Reproduced verbatim from `BRAND.md` v1.1. These govern every asset in this repo.*

{ANNEX}

---

## Manifest
{tree()}
---

## The loom

`tools/` holds the generator that produced every derived file here. It is committed so the
**seed-reproducibility guarantee is verifiable from this repo alone, forever** — the seed is the
design, and the loom is what proves it.

```bash
brew install cairo                        # native dep; apt-get install libcairo2 on Debian
pip install -r tools/requirements.txt
python3 tools/gen.py                      # motifs, fields, bands, mixed, contact sheet, marks
python3 tools/docs.py                     # css + this README
```

`gen.py` is idempotent: running it on a clean checkout reproduces every tracked file
byte-for-byte. `docs.py` imports `gen.py` as a model and emits nothing on import.

---

## Provenance

| Asset | Source | Method |
|---|---|---|
| Five Folk motifs | `sources/*.svg`, 20px module | Parsed to integer grids; zero off-module rects |
| Motif dialects | the same grids | `stitch` = rx 4.6; `crisp` = rx 0. Colors verbatim, never recolored |
| Fields | motif silhouettes | Re-laid on the 8px stitch grid, one ink, one strength |
| Eternal Thread | `popescuportfolio/assets/case.css` `.thread-band` | Copied verbatim (48x16 source coords) |
| Light Trim | Canon vault measurement | 32x8, four 5x5 stitches, staggered |
| Deco Band | Canon tile spec | 88x66, 4x3 grid of 22px cells |
| Marks | `sources/pop-logo-{{color,mono}}.png` | Copied untouched (byte-identical) |

### Why `sources/` is tracked
The five motif SVGs and both logo PNGs are **not** redundant with `motifs/` and `marks/`.
`motifs/` files are re-serialised into two dialects and are build output; the logos in `marks/`
are byte-identical copies. The loom reads `sources/` at build time, so removing it would break
reproducibility — the one thing this repo must guarantee. They stay, relocated from the repo
root into `sources/` to separate input from output.

---

## Canon interpretations

Two readings were required during the export and are **blessed as canon**:

**1. `stem-bloom`'s ivory cells are negative space, not ink.** The motif carries a 4-cell ivory
`{G.IVORY}` knockout at its centre. Ivory is a ground color, so those cells are holes: the field
silhouette omits them (50 cells -> 46 inked). No other motif is affected; every other silhouette
is 1:1 with its cell count.

**2. Peri is a mid ground and takes shadow @0.18.** FIELD LAW's ink flip is triggered by *dark*
grounds. Only abyss (and future dark grounds) take peri `{G.PERI}` @0.16. Peri `{G.PERI}` used
*as a ground* is a mid tone and carries shadow `{G.SHADOW}` @0.18 like ivory, yellow, pink, and
vermilion.

### Ink selection (FIELD LAW v1.2)
| Ground | Hex | Ink | Strength |
|---|---|---|---|
| ivory | `{G.IVORY}` | shadow `{G.SHADOW}` | 0.18 |
| yellow | `{G.YELLOW}` | shadow `{G.SHADOW}` | 0.18 |
| pink | `{G.PINK}` | shadow `{G.SHADOW}` | 0.18 |
| vermilion | `{G.VERM}` | shadow `{G.SHADOW}` | 0.18 |
| peri | `{G.PERI}` | shadow `{G.SHADOW}` | 0.18 |
| abyss | `{G.ABYSS}` | peri `{G.PERI}` | 0.16 |

All fields here are decorative, so all use **0.18 standard** (0.16 on dark). The 0.13 whisper
strength is reserved for fields behind readable content and is not exported in this pack.

Spot-check: shadow on yellow at 0.18 composites to `{G.rgb2hex(G.over(G.SHADOW, G.YELLOW, 0.18))}` — dusty olive, as specified.

---

## Bands

| Band | Native | Ground | Notes |
|---|---|---|---|
| Eternal Thread | 54x18 | abyss bed | **Dark grounds only** |
| Light Trim | 32x8 | transparent | **Light grounds only**; strip = unit x24 = 768x8 |
| Deco Band | 88x66 | white | Editorial moments; `band_deco-strip.svg` is the 4-repeat |

### Usage note: Light Trim on yellow
Light Trim on a yellow ground is legal — light ground, canon pigments, nothing to fix. But the
yellow stitch goes silent against it, and a quarter of the band's voice drops out. Prefer ivory
or another light ground when all four stitches should read. This is guidance, not law: if the
muted reading is what you want, take it.

### Ruling: Eternal Thread's 48x16 -> 54x18 is not a scaling operation
BAND LAW fixes Eternal Thread at **18px**. The 48x16 tile is *source coordinates*; x1.125 is
simply what "18px tall" means for that tile. It is the voice's definition, not a transform.
BAND LAW v1.2's print-scale clause governs scaling a voice **beyond its native size**
(18 -> 36, 8 -> 16), and that clause is fully in force above 18px. Not a deviation.

---

## Seeds (SHUFFLE LAW)

Every mixed field carries its seed; **the seed is the design**. Layouts are a 4x4 grid of
16x16-cell slots, each slot drawing one of the Folk Five by seeded random choice, motif centred
in its slot. Neutral surfaces shuffle evenly, so selection is uniform across all five — no totem
weighting.

The generator is a documented LCG, so any seed regenerates identically:

```
state = seed
state = (state * 1664525 + 1013904223) mod 2^32     # advance
r     = state / 2^32                                 # in [0,1)
index = floor(r * 5)                                 # into the Folk Five, in canon order
```

Canon order: `{', '.join(G.MOTIFS)}`.

Each SVG records its own seed in a `data-seed` attribute. A seed produces one layout, which is
then rendered on each ground — so `mix_s7_ivory` and `mix_s7_abyss` are the same design in two
worlds.

**All 20 seeds reviewed and Commander-approved, 28 July 2026. The full set is canon.** No
pruning; `contact-sheet.png` is the approved record of the set, not a shortlist.

---

## Usage

**Data-URI paste.** `css/bands-and-fields.css` carries every band and field as a self-contained
background rule. No asset requests, no build step:

```html
<div class="field-diamond-eye-ivory">...</div>
<div class="band-eternal-thread"></div>
```

**PNG @2x for Figma and print.** Field PNGs are 960x960 (2x of the 480 swatch) — drop straight
into Figma as an image fill, or place in print at up to 50% scale for 300dpi output.

**SVG for anything that scales.** Field SVGs use a `<pattern>`, so resizing the frame re-tiles
rather than stretching the motif.

### Prohibitions that bite in practice
- Never rotate a motif — translation is its only legal motion.
- Never mix dialects in one field.
- Bands never swap grounds: Eternal Thread on dark only, Light Trim on light only.
- Scaling a band beyond native is whole-number and aspect-locked. Never scale on one axis.
- Never introduce a color outside the twelve canon hexes. When contrast fails, change the
  pairing, never the pigment.

---

## Known deviations (logged, not fixed here)

1. **The 0.13 whisper strength is not exported.** Only decorative strengths ship in this pack.
2. **`ink-deep` homepage drift.** `BRAND.md` logs the deployed cards at ink-deep `{G.INKDEEP}`
   @0.13; this pack uses shadow `{G.SHADOW}` throughout, per the vault's one-ink rule.
3. **Dashboard app files relocated.** `globals.css`, `layout.tsx`, and `page.tsx` were found at
   this repo's root. They are dashboard deployment files, not brand-kit files; they were moved
   to `../brand-kit-attic/` on disk (outside this repo) and removed from tracking. Nothing was
   deleted. Their final home is a separate decision.
"""
G.wf(f"{OUT}/README.md", readme)
print("wrote README.md, css/bands-and-fields.css, tools/requirements.txt")
print("annex bytes:", len(ANNEX))
